export async function checkInspection({ evaluate, until, check, shot, send, sleep, key, evidence, record, failModels }) {
  const stats = `JSON.parse(document.querySelector('.model-viewer').dataset.stats || '{}')`;
  await shot('01-overview');
  await evaluate(`rhineSshUi.connectHost('review-host')`);
  await until('inspection loaded', `${stats}.ready`);
  await check('a host can be inspected without connecting or opening a terminal', `!rhineSsh.active && !rhineSshUi.isOpen && !document.querySelector('[data-viewer="primary"]').hidden`);
  await check('terminal inspection owns nine shell and insert layers', `${stats}.parts.length === 9 && ${stats}.parts.every(part => part.meshes > 0)`);
  await shot('02-model-assembled');
  await record(true);
  const before = await evaluate(`${stats}.cameraPosition`);
  await send('Input.dispatchMouseEvent', { type: 'mousePressed', x: 800, y: 500, button: 'left', clickCount: 1 });
  await send('Input.dispatchMouseEvent', { type: 'mouseMoved', x: 940, y: 540, button: 'left', buttons: 1 });
  await send('Input.dispatchMouseEvent', { type: 'mouseReleased', x: 940, y: 540, button: 'left', clickCount: 1 });
  await sleep(450);
  await check('dragging rotates the inspection camera', `Math.abs(${stats}.cameraPosition[0] - ${before[0]}) > .1`);
  const distance = await evaluate(stats + '.distance');
  await send('Input.dispatchMouseEvent', { type:'mouseWheel', x:800, y:500, deltaX:0, deltaY:-120 });
  await sleep(450);
  await check('wheel zoom changes the camera distance', stats + '.distance < ' + distance);
  await key('ArrowRight', 'ArrowRight', 39);
  await sleep(400);
  await check('arrow keys pan the inspection', stats + '.targetPosition.some(value => Math.abs(value) > .01)');
  await key('Home', 'Home', 36);
  await sleep(650);
  await evaluate(`document.querySelector('[data-viewer="explode"]').click()`);
  await until('layers separated', `${stats}.spread === 1`);
  await shot('03-model-exploded');
  evidence.exploded = await evaluate(stats);
  await check('explosion keeps each layer on its assembly axis', `${stats}.parts.every(part => part.x === part.restX && part.y === part.restY)`);
  await check('exploded layers have six percent width clearance', `${stats}.clearance >= .0599`);
  const rotated = await evaluate(`${stats}.azimuth`);
  await evaluate(`document.querySelector('[data-viewer="assemble"]').click()`);
  await sleep(180);
  const mid = await evaluate(`${stats}.spread`);
  await evaluate(`document.querySelector('[data-viewer="explode"]').click()`);
  await check('reversing explosion retains the intermediate pose', `${stats}.spread > 0 && ${stats}.spread < 1`);
  await until('reversed layers settle', `${stats}.spread === 1`);
  await check('reassembly does not reset the orbit', `Math.abs(${stats}.azimuth - ${rotated}) < .001`);
  await record(false);
  for (const [width, height, scale] of [[800,600,1],[1366,768,1],[1920,1080,2],[2560,1440,1]]) {
    await send('Emulation.setDeviceMetricsOverride', { width, height, deviceScaleFactor: scale, mobile:false });
    await sleep(350);
    await check(`inspection controls fit ${width}x${height} at ${scale}x`, `Array.from(document.querySelectorAll('.viewer-footer button,.viewer-primary')).every(node => { const r=node.getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth && r.top >= 40 && r.bottom <= innerHeight; })`);
    await shot(`model-${width}-${scale}x`);
  }
  await send('Emulation.setDeviceMetricsOverride', {width:1920,height:1080,deviceScaleFactor:1,mobile:false});
  await evaluate(`document.querySelector('[data-viewer="primary"]').click()`);
  await until('explicit entry asks for authentication', `rhineSshUi.promptKind === 'password' && document.querySelector('.model-viewer').hidden`);
  await evaluate(`rhineSshUi.answerSecret('inspection-test'); __deckFixture.interactive()`);
  await until('explicit entry opens terminal', `rhineSshUi.hasFocus`);
  await sleep(250);
  await check('terminal has no teardown or scan animation', `!document.querySelector('.ssh-terminal-teardown') && getComputedStyle(document.querySelector('.ssh-terminal')).animationName === 'none' && getComputedStyle(document.querySelector('.ssh-terminal'),'::after').content === 'none'`);
  await shot('04-terminal');
  await evaluate(`rhineSshUi.closeTerminal()`);
  await until('returning opens inspection without disconnecting', `!document.querySelector('.model-viewer').hidden && ${stats}.ready && !rhineSshUi.isOpen`);
  await check('return to model preserves the live connection', `rhineSsh.active`);
  await key('Escape', 'Escape', 27);
  await until('inspection dismissed', `document.querySelector('.model-viewer').hidden`);
  await evaluate(`__deckFixture.end(0)`);
  await evaluate(`rhineSshUi.startSession({ target:'review-host', displayName:'Silent preparation' })`);
  await until('preparation auth', `rhineSshUi.promptKind === 'password'`);
  await evaluate(`rhineSshUi.answerSecret('prepare'); __deckFixture.interactive()`);
  await sleep(800);
  await check('connection success without entry intent never steals the view', `rhineSsh.status().phase === 'interactive' && !rhineSshUi.isOpen`);
  evidence.reversalSpread = mid;
  await evaluate(`localStorage.setItem('rhine-settings', JSON.stringify({...JSON.parse(localStorage.getItem('rhine-settings')), reduced:true}))`);
  failModels(true);
  await send('Page.reload');
  await until('fallback app loaded', 'window.rhine?.stats().ready && !!window.rhineSshUi');
  await evaluate(`rhineSshUi.connectHost('review-host')`);
  await until('inspection failure is recoverable', `document.querySelector('[data-viewer="retry"]')?.hidden === false`);
  await check('failed model still offers a regular terminal entry', `!document.querySelector('[data-viewer="primary"]').disabled && !rhineSshUi.isOpen`);
  await shot('05-model-fallback');
  await evaluate(`document.querySelector('[data-viewer="primary"]').click()`);
  await until('fallback authentication', `rhineSshUi.promptKind === 'password'`);
  await evaluate(`rhineSshUi.answerSecret('fallback'); __deckFixture.interactive()`);
  await until('fallback terminal opens', 'rhineSshUi.hasFocus');
  await check('fallback uses unscaled native terminal with reduced motion', `rhine.stats().motion.reduced && document.querySelector('.ssh-terminal').dataset.presentation === 'window'`);
  failModels(false);
  await send('Page.reload');
  await until('reduced app loaded', 'window.rhine?.stats().ready && !!window.rhineSshUi');
  await evaluate(`rhineSshUi.connectHost('review-host')`);
  await until('reduced inspection loaded', stats + '.ready');
  await evaluate(`document.querySelector('[data-viewer="explode"]').click()`);
  await sleep(50);
  await check('reduced motion reaches the exploded target immediately', stats + '.spread === 1');
  await evaluate(`document.querySelector('[data-viewer="assemble"]').click()`);
  await sleep(50);
  await check('reduced motion reaches the assembled target immediately', stats + '.spread === 0');
  await key('Escape','Escape',27);
  await check('dismissed inspection cannot start a connection', '!rhineSsh.active && !rhineSshUi.isOpen');
}
